### PR TITLE
8 Letter Wordle 

### PR DESCRIPTION
**Pull request by 4thehalibit**
Followed instructions to change the three files this is an 8 letter wordle. Not sure how to share with others or if this will work. I tried once before and none of my words were "found" I know the word Thirteen is in my list 

any help is appreciated

### CODE REVIEW

**Comment by joedel263** [comment]
your word lists should be completely lowercase, otherwise the script won't be able to match what's there

**Comment by 4thehalibit** [comment]
> your word lists should be completely lowercase, otherwise the script won't be able to match what's there

Thank you that did the trick. Do you have any tips on changing name and creating a unique link

**Comment by joedel263** [comment]
you can edit the name and title of the game in the file .env

by unique link, do you mean having it at it's own domain?
the command "run npm build" will create all of the files (in the build folder) to upload it where you want.

**Comment by 4thehalibit** [comment]
> you can edit the name and title of the game in the file .env
> 
> 
> 
> by unique link, do you mean having it at it's own domain?
> 
> the command "run npm build" will create all of the files (in the build folder) to upload it where you want.

Ahh the .env file makes sense. I was overlooking that because there wasn't a language change.

Unique name I am talking like 'reactle.vercel.app' something easy to share instead of 'https://react-wordle-git-fork-4thehalibit-main-cwackerfuss.vercel.app'

**Pull request closed without merging**
