### PR TITLE
Unicode character handling fix

### PR DESCRIPTION
**Pull request by gheja**
Fixes the issue when using letters using more than one unicode characters - see issue #203 

I updated the length check, display in grid, enter and delete operations as well. It looks good to me but probably needs more testing.

I have modified the keyboard to have unicode characters, like this:
```patch
diff --git a/src/components/keyboard/Keyboard.tsx b/src/components/keyboard/Keyboard.tsx
index 485e8b3..5788dd4 100644
--- a/src/components/keyboard/Keyboard.tsx
+++ b/src/components/keyboard/Keyboard.tsx
@@ -77,7 +77,7 @@ export const Keyboard = ({
         <Key width={65.4} value="ENTER" onClick={onClick}>
           {ENTER_TEXT}
         </Key>
-        {['Z', 'X', 'C', 'V', 'B', 'N', 'M'].map((key) => (
+        {['Z', 'X', 'C', 'V', 'B', 'N', '\u0BAE\u0BC1'].map((key) => (
           <Key
             value={key}
             key={key}
```

### CODE REVIEW

**Review by cwackerfuss — APPROVED** [review]
This looks awesome and works well after testing locally. Thanks for this @gheja

**Comment by cwackerfuss** [comment]
Oops - it looks like there is a merge conflict with main. Can you please address this and then we can merge

**Comment by muhelen** [comment]
Its still didn't fix the MAX_WORD_LENGTH issue. The unicode characters still count as separate characters, which in return affecting the length number.

**Comment by muhelen** [comment]
Now **NOT_ENOUGH_LETTERS_MESSAGE** working fine. The unicode characters combination could be up to 5 letters, but the last letter couldn't combine fully. For example, it could enter as **ம** but ம+் which in return supposed to be ம் not working..

**Comment by muhelen** [comment]
The last grid don’t combine Tamil unicode  characters. Anyone else having this issue on other languages?

**Comment by gheja** [comment]
Good to hear, I am glad it works.

Thank you so much, and all the best for you too!

@cwackerfuss, I think we have fixed everything, could you check it? Thanks!

**Comment by cwackerfuss** [comment]
Looks awesome thanks all!

**Pull request merged**
