### PR TITLE
added missing words to validGuesses.ts

### PR DESCRIPTION
**Pull request by stenkast**
Fixes Issue #465 as well as adding 139 other words in wordlist.ts that were missing from validGuesses.ts.

I basically just wrote simple code to go through every word in wordlist, and make sure it is included in validGuesses, and console.log if it's not. So it should be pretty fool proof and make sure that there are no more such errors.

These are the words that were missing from validGuesses:

> versa, annum, facto, toves, yella, wanta, garde, mebbe, carne, dewey, latin, hubba, ahhhh, heerd, outen, faire, facie, quals, neato, adlib, chiff, yoyos, bossa, oodle, poset, anded, hafta, gouda, jings, offen, thwap, thats, ohhhh, tagua, forma, bueno, dieth, choos, bronx, harum, laude, plein, humpf, seest, watsa, mecum, whooo, mrads, astro, grata, klunk, pssst, lulab, fugit, wheee, injun, didot, wassa, magna, rebox, bhoys, juste, musta, epsom, belli, herem, vivre, noire, firma, dictu, mumbo, vacuo, excon, diems, vitam, whoas, deque, treap, acked, poste, faxer, nurbs, pismo, ioctl, gronk, greps, pooey, seeth, ville, pffft, oring, klugy, shnor, liest, nerfs, ghoti, luvya, unate, defun, oweth, tribs, tecum, utero, smurf, owest, ftped, barfy, rasae, ahoys, lieth, hadda, lilty, arity, finif, oinky, shiki, legos, buena, unmap, diest, turdy, lawzy, cordy, mungy, carpy, grook, xored, fanin, unhit, etext, holer, dicut, bebug, inode, dovey, crink, unarc, shmoo, abend, assed

### CODE REVIEW

**Comment by igitur** [comment]
ahhhh?
pssst?

**Comment by stenkast** [comment]
> ahhhh? pssst?

Yes?

**Comment by igitur** [comment]
To me, those aren't words. Wordle also doesn't accept them. From where did you source this list?

**Comment by stenkast** [comment]
> To me, those aren't words. Wordle also doesn't accept them. From where did you source this list?

This one? This is literally words you will find in wordlist.ts, that are missing from validGuesses.ts... So if they are ever used in the game, you won't be able to ever guess the word correctly.

**Comment by igitur** [comment]
I will have to double-check, but I believe if a word is in the list of solutions (`wordlist.ts`) then it's not required for it to be in `validGuesses.ts` too.

Anyway, I'd rather remove those words from `wordlist.ts`.

**Comment by stenkast** [comment]
> I will have to double-check, but I believe if a word is in the list of solutions (`wordlist.ts`) then it's not required for it to be in `validGuesses.ts` too.

If that's true, then every word in wordslist.ts should be removed from validGuesses.ts to prevent unnecessary duplicated words. That's my OCD brain take at least.

> Anyway, I'd rather remove those words from `wordlist.ts`.

There is probably a lot more words that should get booted in that case. Which anyone is free to go through 6000 words if they wish.

**Comment by igitur** [comment]
Hang on... I still want to merge this, but I'm definitely going to remove ahhhh ;-) . And I totally understand the OCD comment!

**Pull request merged**
