### PR TITLE
Removes modal scroll where not needed and modal centering

### PR DESCRIPTION
**Pull request by stenkast**
This removes the modal scroll when it's not needed, and also makes it so the modal respects the height, especially on Safari. Also changes the way it's centering to remove the need for the trick div, if it's required I'll put it back.

### CODE REVIEW

**Comment by stenkast** [comment]
Brain is working a bit faster than I can handle. I just realized this is going to need the changes made in #514 first. So I'll close it for now and pick it up later.

**Comment by igitur** [comment]
After #488 and #516 , I don't see scrollbars. Is this PR still necessary?

**Comment by igitur** [comment]
Can you please post before and after screenshots to illustrate the problem and solution?

**Comment by stenkast** [comment]
https://i.imgur.com/Z67Sx6t.png

Left is before, Right is after. It's not really possible to show the scrolling, that's something you'll just have to check yourself.

**Comment by igitur** [comment]
I can see the issue in your screenshot, but I fail to reproduce it on any device. Do you think this is, again, something specific to iOS/Safari? Would you mind confirming that you cannot reproduce it on Chrome/Android on https://reactle.vercel.app/ ?

**Comment by igitur** [comment]
posted under correct PR ;-)

**Comment by stenkast** [comment]
Yeah, it seems to be a Safari issue again, yikes Apple.

**Review by igitur — APPROVED** [review]

**Comment by igitur** [comment]
Thanks!

**Pull request merged**
