### PR TITLE
Converted the modal close div to a button.

### PR DESCRIPTION
**Pull request by igitur**
> This makes the app more accessible and allows keyboard only users to close out of the modal easily.

Alternate implementation to #364

Closes #364

### CODE REVIEW

**Comment by igitur** [comment]
cc @Bracciata , @gheja Check preview at https://react-wordle-git-fork-igitur-pr-364-close-button-cwackerfuss.vercel.app/

**Comment by igitur** [comment]
I think the NavBar could use the same love.

**Comment by gheja** [comment]
Looks great and works fine, thank you!

**Comment by igitur** [comment]
@Bracciata Are you happy that we rather go with this PR?

**Pull request merged**
