### PR TITLE
Added German Harry Potter wordle to Readme.md

### PR DESCRIPTION
**Pull request by A-wels**
Since this does not really fit into the existing categories, I added a new one. I feel like adding this to the normal 'fun themes' list would make the list worse for the majority of users, while using the 'other languages' list would not fit into the 'default wordle' theme of the list.

### CODE REVIEW

**Comment by igitur** [comment]
Agree, but please add the new category directly below the `Fun Themes` category instead of below the `Maths` category.

**Comment by igitur** [comment]
I'm getting HTTP 502 for your site.

**Comment by A-wels** [comment]
Whoops, I was rebuilding the site. It should work now.

**Comment by A-wels** [comment]
The order of categories has also been changed as requested

**Pull request merged**
