### PR TITLE
Add Colordle to readme

### LINKED ISSUE #280: Add Colordle to the list of spinoffs
I did a silly fork where you guess hexadecimal color codes :stuck_out_tongue: 

https://github.com/necropolina/colordle
https://colordle.vercel.app/

### PR DESCRIPTION
**Pull request by necropolina**
resolves #280

### CODE REVIEW

**Comment by igitur** [comment]
@cwackerfuss Maybe we should start maintaining these list of implementations in alphabetical order?

**Comment by necropolina** [comment]
> @cwackerfuss Maybe we should start maintaining these list of implementations in alphabetical order?

Done!

**Review by igitur — APPROVED** [review]
Will require a `Squash and Rebase` merge strategy.

**Comment by cwackerfuss** [comment]
@igitur - we do maintain them in alphabetical order -- there is some light organization (languages, fun, math/technology) which I think has worked nicely.

**Review by cwackerfuss — APPROVED** [review]

**Pull request merged**
