### PR TITLE
Implemented a navbar like the original wordle

### PR DESCRIPTION
**Pull request by abrarhayat**
Implemented a navbar like the original wordle.

### CODE REVIEW

**Comment by 4thehalibit** [comment]
> Implemented a navbar like the original wordle.

Awesome job I just merged this into my "Unnecessary" 8 letter Wordle It looks fantastic

**Comment by muhelen** [comment]
This look very 👍🏼. On dark mode the line looks thick white. If could reduce the thickness would be great. Thanks for your contribution 🙏🏼.

**Comment by abrarhayat** [comment]
@muhelen I added a simple horizontal line. Didn't add any styling.

**Review by cwackerfuss — APPROVED** [review]

**Comment by cwackerfuss** [comment]
LOVE IT thank you!

**Pull request merged**
