### PR TITLE
Add docker-compose.yaml

### PR DESCRIPTION
**Pull request by nbeck415**
Hey there! I found this project when looking for fun Dockerized apps, and I have really enjoyed exploring it and its many forks. I featured it in a beginner Docker Compose tutorial post, in which I show how to write a Compose file based on the Docker commands. It was a great learning experience for me!

I just wanted to open a PR with the final Compose file, please let me know if there's anything else I should add to this!

### CODE REVIEW

**Comment by igitur** [comment]
Hi, thanks for this. I'm a docker build novice and was unable to get the container up and running using this supplied `docker-compose.yaml` file. Can you please point me to your tutorial so that I ensure that I followed the correct steps?

**Comment by nbeck415** [comment]
Hey, thanks for trying it out! I realized you uncovered a bug in my compose definition that I wasn't seeing locally. I am working on revising the file, editing the tutorial, and then will get back to you shortly with the correct fixes!

**Comment by nbeck415** [comment]
Hey, just got this working, thank you for your patience! If you'd like to check out the tutorial it's [here](https://shipyard.build/blog/react-wordle-with-docker-compose/), and all you really need to do is run `docker compose up` from the root directory!

**Comment by igitur** [comment]
Thanks. This looks good and I'll play around with my own derivative implementation on Shipyard. I see it starts up the dev server and exposes only port 3000. Is there an option to spin up the production build and expose port 8080?

**Comment by nbeck415** [comment]
Glad that fixed things!

I think the best way to do that would be adding another service to the Compose file that defines the production build. It might be something like:
```yaml
reactle-prod:
    build:
        context: .
        dockerfile: docker/Dockerfile
        target: prod  
    ports:
        - '80:8080'
```
If you have an image for your own implementation you might want to add it in here too under an `image` tag, but this builds quickly enough that I don't think its super necessary.
 
You'd run the prod service using `docker compose up -d reactle-prod`. This worked on my end, please let me know if there's anything else you need to get things up and running :)

**Comment by igitur** [comment]
Are you OK with me changing the indentation to 2 spaces?

**Comment by nbeck415** [comment]
For sure, that is okay!

**Comment by igitur** [comment]
Thanks for the contribution. I'll link to your tutorial in our README.

**Comment by nbeck415** [comment]
Thanks for reviewing it! Always happy to contribute more to this project :)

**Pull request merged**
