### PR TITLE
Now highlighting the current day stat in stats modal

### PR DESCRIPTION
**Pull request by abrarhayat**

### CODE REVIEW

**Comment by abrarhayat** [comment]
Made an attempt to highlight the current day stat row. Need opinion on the highlight color.

**Comment by igitur** [comment]
I'd say the current blue for the highlight colour and same gray / charcoal as Wordle for the other.

**Comment by abrarhayat** [comment]
@igitur Done.

**Review by cwackerfuss — APPROVED** [review]
Awesome - thank you @abrarhayat !

**Pull request merged**
