### PR TITLE
Added High Contrast Mode

### PR DESCRIPTION
**Pull request by bluswimmer**
Added a high contrast mode that can be turned on in the settings modal. This changes the squares from yellow and green to cyan and orange, including when you share your game.

### CODE REVIEW

**Comment by bluswimmer** [comment]
Need to make an additional commit to resolve a visual bug, will report back in a bit...

**Review by cwackerfuss — CHANGES_REQUESTED** [review]
I think it would be more useful to call the localStorage item `highContrast` or something and set its value to either `"true"` or `"1"`. We are not maintaining the "low" value, so lets just delete this if it gets unset.

I know this practice hasn't been used consistently, but lets abstract the use of localStorage into helper fns. There is a file called `localStorage.lib` that we can put these in. I think the React app shouldn't have to do an equality check inline either with this method if you just make the get helper return a boolean.

For example, we can set the `isHighContrastMode` like so:
```
const [isHighContrastMode, setIsHighConstrastMode] = useState(() => getStoredIsHighContrastMode())
```

**Review by cwackerfuss — APPROVED** [review]
Looks good to me - one improvement you could make if you'd like to is to call `getStoredIsHighContrastMode` only once and store as a variable in each of the files it's being called several times, but I'm fine also merging this and addressing that later.

**Comment by cwackerfuss** [comment]
And yes -- I do think we should do dark mode / hard mode in the same way. Great point

**Pull request merged**
