### PR TITLE
improve layout of header

### PR DESCRIPTION
**Pull request by cwackerfuss**
I've been unhappy with how much margin there is currently at the top of the page. This reduces the margin and improves the positioning of the alert.

I also removed the SVG hover animation since it felt a little awkward and occasionally bugs out the cursor when you're hovering on the very bottom of the icon.

Screen Shot 2022-02-15 at 10 58 58 PM

### CODE REVIEW

**Comment by diondiondion** [comment]
This is much better!

However, I have a very tall phone and the keyboard is quite high up now. Could you add some CSS that makes sure the keyboard is pushed to the bottom of the page when there's space? If the outer container matches the height of the viewport, making it a flex (column) container and adding `margin: auto 0` to the grid in the middle may do the trick.

**Comment by gheja** [comment]
There is one more open issue with playing on smaller screens: #188

I've been thinking about adding CSS Media Queries to modify the margins based on screen size (or aspect ratio?) but haven't got the time to create a set with reasonable cover of the possible cases.

**Comment by zbennett** [comment]
What is the latest with this PR? I really like this change.

**Comment by cwackerfuss** [comment]
Hi @zbennett - I can take a look at this when I'm back tomorrow - had a vacation this week. :)

**Comment by zbennett** [comment]
I love every part of that statement.

**Comment by cwackerfuss** [comment]
Added a flex column layout to the outermost app container of 100vh and made the guesses section flex-grow to fill space - just merged thanks all!

**Comment by vegeta897** [comment]
Unfortunately 100vh is problematic on iOS with Chrome and Safari.

image image

If there was a good solution out there or if I was more familiar with react and tailwind I'd try to make a PR, but for now I just wanted to bring this to your attention. I can open an issue if that would be helpful.

**Pull request merged**
