### PR TITLE
Added TwoKinds to list

### PR DESCRIPTION
**Pull request by eithe**
I made an out of the box spin-off where you select between two pictures which in the end sort of determines who you are.

https://twokinds.me

### CODE REVIEW

**Comment by abrarhayat** [comment]
Nice!

**Comment by soumendrak** [comment]
Good one

**Comment by igitur** [comment]
@eithe Link is dead. Please fix or remove from README.

**Comment by eithe** [comment]
Thanks for letting me know, @igitur.

https://github.com/cwackerfuss/react-wordle/pull/636

**Pull request merged**
