### PR TITLE
react-div-100vh + responsive content

### PR DESCRIPTION
**Pull request by igitur**

### CODE REVIEW

**Comment by igitur** [comment]
@stenkast Try out https://react-wordle-git-safari-padding-npm-package-cwackerfuss.vercel.app/ and let me know, please

**Comment by stenkast** [comment]
It works. Though, you don't center the grid. 

I closed my #508 as I accidentally made the pull request using my main branch, which causes problems if I want to make future PRs. Rookie mistake.

**Comment by igitur** [comment]
Hell, somewhere in one of my branches I *did* center the grid, but I can't find that commit now!

**Comment by igitur** [comment]
@stenkast Ok, it should be centered vertically now.

**Comment by stenkast** [comment]
Looks good

**Comment by igitur** [comment]
Fixed in #488 , #516

**Pull request closed without merging**
