### PR TITLE
Took margin out of settings icon in nav bar to fix formatting. 

### PR DESCRIPTION
**Pull request by zbennett**

### CODE REVIEW

**Comment by igitur** [comment]
I'm known to be quite pedantic, so excuse me. My only comment here would be that the git commit comment should be more descriptive. Something like `"Remove cog igon right margin"` would be more descriptive.

**Comment by igitur** [comment]
@cwackerfuss Hope you don't mind me butting in, but unless you don't want help, I'm going to review some PRs and issues.

**Comment by cwackerfuss** [comment]
Absolutely, I don't mind at all @igitur! Agreed and good catch - let's get an updated commit name, otherwise this change looks fine to me.

**Comment by igitur** [comment]
@zbennett Are you comfortable with rewriting git history, and specifically editing the commit message?

**Comment by zbennett** [comment]
Alright. Done.

**Review by igitur — APPROVED** [review]

**Review by cwackerfuss — APPROVED** [review]

**Pull request merged**
