### PR TITLE
Add Norwegian version to readme.md

### PR DESCRIPTION
**Pull request by magnuslo**
Added the Norwegian version

### CODE REVIEW

**Comment by igitur** [comment]
Several of the old links are broken. If you know how to use git blame, please help me identify the owners of the link and ask them to update or remove the links. See CI output.

**Comment by magnuslo** [comment]
> Several of the old links are broken. If you know how to use git blame, please help me identify the owners of the link and ask them to update or remove the links. See CI output. 

Certainly!

Here's a list of the broken links and from what I've gathered their creators:

[jwordle.vercel.app](https://jwordle.vercel.app/) by @woelpad
[keclap.xyz](https://keclap.xyz/) @ruangchupa
[tacticle.co](https://tacticle.co/) by @morganpartee
[kelmaly.com](https://kelmaly.com/) - by @MohammedAlrozzi
[movie-wordle.vercel.app](https://movie-wordle.vercel.app/) by @bhavesh15184
[rwordle.vercel.app](https://rwordle.vercel.app/) by @aghasemi
[wordle.cl](https://www.wordle.cl/) by @jtraverso

**Comment by woelpad** [comment]
NY Times asked me (or rather Vercel, on which computers the app is running)
to shut it down because of "trademark infringement". This was just last
week. I'm guessing I'm not the only one treated this way.

**Comment by igitur** [comment]
@woelpad @ruangchupa @morganpartee @MohammedAlrozzi @bhavesh15184 @aghasemi @jtraverso Please submit a PR to remove the link to your site if it's not valid anymore.

**Comment by magnuslo** [comment]
> @magnuslo Do you pinky swear to maintain your Nordle link and remove it from this list if it becomes inactive.

I do 🫶

**Pull request merged**
