### PR TITLE
Add ability to play a past date

### LINKED ISSUE #178: Allow to go back in time to do older words
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to go back in time to do words of past days.

**Describe the solution you'd like**
I guess we could add a button to switch the date.

**Describe alternatives you've considered**
For now I'm using other non open source app that allow that.

### LINKED ISSUE #500: Old Word Archive
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to go back in time to do words of past days. An Archive modal would be a great idea.

### PR DESCRIPTION
**Pull request by igitur**
This is my first stab at allowing players to choose a past date.

I still have to update the README.

`settings.ts`:
- `ENABLE_ARCHIVED_GAMES`: set to to `true`
- `DATE_LOCALE`: set to correct locale and change the import at the top. Choose one from https://github.com/date-fns/date-fns/tree/main/src/locale

`strings.ts`:
- Update `DATEPICKER_TITLE`, `DATEPICKER_CHOOSE_TEXT`, `DATEPICKER_TODAY_TEXT` and `ARCHIVE_GAMEDATE_TEXT`

How it works:
- Enabling archived games adds the new calendar icon in the nav bar. The date picker is constrained to dates between `firstGameDate` (defined in `words.ts`) and 'yesterday'. Choosing a date reloads the page with a query parameter, e.g. `http://localhost:3000/?d=2022-05-11` from which the game date is read.
- Solving or failing past games doesn't affect the user's statistics, e.g. his current and best runs.
- The past game state is stored in a new key in local storage, so the user can navigate away, come back and reload the page (with the query string) and continue his game. This doesn't affect the 'live' game.
- When playing a past date's game, a new label is shown between the navbar and the grid so that the user has no doubt that a past game is being played. I'm open to better UX design here.

Fixes #500 
Fixes #178

### CODE REVIEW

**Comment by igitur** [comment]
@muhelen @gheja @TheKnowles Your feedback on this PR, if you can?

Preview link: https://react-wordle-git-fork-igitur-datepicker-cwackerfuss.vercel.app/

**Comment by TheKnowles** [comment]
I need to play with it some more, but the first thing I noticed right off the bat is the UTC versus whatever I am using the browser. This delays the date by a day.

i.e. I pick Aug 1, it shows July 31, etc...

**Comment by igitur** [comment]
> I need to play with it some more, but the first thing I noticed right off the bat is the UTC versus whatever I am using in the browser. This delays the date by a day.
> 
> i.e. I pick Aug 1, it shows July 31, etc...

Thanks. In which time zone are you? I'm at GMT+2, so probably on the other side of UTC than you are, hence I haven't noticed these issues.

**Comment by TheKnowles** [comment]
EST/EDT or UTC -4
reactle

**Comment by igitur** [comment]
@TheKnowles Thanks. I just discovered https://stackoverflow.com/a/33909265/179494 . Why does JS always have to be so complicated?!

**Comment by igitur** [comment]
Ok, I'm using `parseISO` from the `date-fns` library now. I temporarily set my timezone to UTC-4 and it worked for me. Please retry.

**Comment by TheKnowles** [comment]
LGTM! Ran through several dates and played a few games.

**Pull request merged**
