### PR TITLE
Add Bininj Kunwok to README

### PR DESCRIPTION
**Pull request by dannykennedy**

### CODE REVIEW

**Comment by igitur** [comment]
@elmurod1202 Can we remove your link?

**Comment by elmurod1202** [comment]
> 

Hi there, sure, no problem, I stopped paying for the hosting, as the interest was lost to the website

**Comment by igitur** [comment]
@dannykennedy Please remove the broken link from the README. See the CI build step for details.

**Comment by dannykennedy** [comment]
OK that's done @igitur 👍

**Review by igitur — APPROVED** [review]

**Comment by igitur** [comment]
@dannykennedy I had to Google Bininj Kunwok a bit. Can you actually speak it?

**Comment by dannykennedy** [comment]
Thanks @igitur . I can actually! To a basic conversational level at least. I worked for a couple of years in a town called Gunbalanya where it's spoken, and I've been helping with the dictionary (at [njamed.com](https://www.njamed.com/)) ever since...

**Comment by igitur** [comment]
Great stuff, well done.

**Comment by dannykennedy** [comment]
thanks, and thanks for your help on this project!

**Pull request merged**
