### PR TITLE
Added cell animation on row complete.

### PR DESCRIPTION
**Pull request by TheKnowles**
This PR adds per cell X axis rotation on word submission. 

From left to right, each letter cell will rotate on its X axis and reveal its status at the end of the animation.

This is achieved with css animation and a little state keeping on the react side.

### CODE REVIEW

**Comment by diondiondion** [comment]
Cool, this is a great start!

Just two notes:
- The letters rotate along with the background which looks quite glitchy (as they only do a half rotation and then snap into place). Ideally the flip animation would only affect the background with the letters remaining static over the top. This would probably require a refactor to separate the background to its own element or pseudo element.
- When winning the game, the alert pops up before the animation has finished, spoiling the effect a bit. Would be great if it could be delayed by the duration of the animation

**Comment by TheKnowles** [comment]
Thank you for the feedback.

Timer delays have been updated to not spoil the reveal of a success or failure.

Cell now has a child div for the letter content. A second animation plays on this child element to avoid the half rotation/snap back glitch.

**Comment by TheKnowles** [comment]
Noticed I was behind on main. Rebased, squashed, and force pushed.

**Comment by cwackerfuss** [comment]
Thank you @TheKnowles and @diondiondion for reviewing. I'm going to merge but I have an idea for how to make this work for any guess length. There are some clones that change the guess length so it'd be nice to support that. If I can get it to work, I'll post a PR and tag both of you

**Comment by soumendrak** [comment]
@TheKnowles 
Can we please delay the keyboard highlight until the cell animation is complete?

**Comment by cwackerfuss** [comment]
@soumendrak I decided to push the changes I made to @TheKnowles code. It will now delay the keyboard highlight until cell animation is complete

**Pull request merged**
