### PR TITLE
Trying to make the histogram style consistent on both ends

### PR DESCRIPTION
**Pull request by abrarhayat**
Trying to make the histogram style consistent on both ends. The semi-circle look looked a bit odd in my honest opinion. Would like to get some feedback.

Now

Proposed

### CODE REVIEW

**Comment by igitur** [comment]
I prefer the rounded corners, but agree that ony the left side being round is weird. Why not makes both ends round? Or only the right side rounded?

I haven't played today's Wordle, but what does that show?

**Comment by abrarhayat** [comment]
The original one has rectangular edges.

**Comment by igitur** [comment]
image

Looks like the spacing between bars is smaller on the original one.

And I like that it highlights the current day's bar.

**Review by cwackerfuss — APPROVED** [review]

**Comment by cwackerfuss** [comment]
Good call - I prefer this too :)

**Comment by igitur** [comment]
> image
> 
> Looks like the spacing between bars is smaller on the original one.
> 
> And I like that it highlights the current day's bar.

I'll try replicate this in a new PR.

**Comment by abrarhayat** [comment]
> 

[Here](https://github.com/cwackerfuss/react-wordle/pull/295) is my solution to this.

**Pull request merged**
