### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by hemantwasthere**
**Changes:**  cool wordle favicon added

**Preview:**  

Screenshot 2022-08-11 133530

### CODE REVIEW

**Comment by igitur** [comment]
Hi, can you please confirm that this icon was created by yourself only and that you release it to this project under the terms of the [license](https://github.com/cwackerfuss/react-wordle/blob/main/LICENSE)?

**Comment by igitur** [comment]
Also, I have to add that I would have preferred an icon that doesn't resemble any of the previous Wordle favions. Do you have time to create something more related to this project?

**Comment by hemantwasthere** [comment]
> Hi, can you please confirm that this icon was created by yourself only and that you release it to this project under the terms of the [license](https://github.com/cwackerfuss/react-wordle/blob/main/LICENSE)?

No it wasnt made by me

**Comment by hemantwasthere** [comment]
> Also, I have to add that I would have preferred an icon that doesn't resemble any of the previous Wordle favions. Do you have time to create something more related to this project?

Yeah i can create a icon for this release

**Pull request closed without merging**
